"""Triton source generation.

Emits one ``@triton.jit`` function per kernel plus a ``LAUNCH`` table the
runtime reads, so the generated module is a standalone artefact you can open
and read. That is deliberate: most of the interesting claims in this project
are claims about the code that gets generated, and they are easier to check
against a file than against a debugger.

Everything the kernel needs is a compile-time constant, because shapes are
static. Element counts are baked into the source, index arithmetic is
constant-folded by :mod:`mlc.codegen.index` before it gets here, and block
sizes are chosen to divide the iteration space where possible so the bounds
mask disappears entirely.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch

from ..config import Config
from ..ir.scalar import Call, Cast, Const, Expr, Load, Ref
from ..kernels import ExternKernel, PointwiseKernel, ReductionKernel, Schedule

TL_DTYPE = {
    torch.float32: "tl.float32",
    torch.float64: "tl.float64",
    torch.float16: "tl.float16",
    torch.bfloat16: "tl.bfloat16",
    torch.int64: "tl.int64",
    torch.int32: "tl.int32",
    torch.int16: "tl.int16",
    torch.int8: "tl.int8",
    torch.uint8: "tl.uint8",
    torch.bool: "tl.int1",
}

#: Narrow floats are loaded and computed in fp32. Reductions in particular are
#: unusable in fp16, and the reference backend makes the same choice so the
#: two agree.
NARROW = (torch.float16, torch.bfloat16)

TRITON_FN = {
    "neg": "(-{0})",
    "abs": "tl.abs({0})",
    "reciprocal": "(1.0 / {0})",
    "exp": "tl.exp({0})",
    "log": "tl.log({0})",
    "sqrt": "tl.sqrt({0})",
    "rsqrt": "tl.rsqrt({0})",
    "sin": "tl.sin({0})",
    "cos": "tl.cos({0})",
    "tanh": "_math.tanh({0})",
    "erf": "_math.erf({0})",
    "sigmoid": "tl.sigmoid({0})",
    "floor": "tl.floor({0})",
    "logical_not": "({0} == 0)",
    "add": "({0} + {1})",
    "sub": "({0} - {1})",
    "mul": "({0} * {1})",
    "div": "({0} / {1})",
    "pow": "_math.pow({0}, {1})",
    "maximum": "tl.maximum({0}, {1})",
    "minimum": "tl.minimum({0}, {1})",
    "gt": "({0} > {1})",
    "lt": "({0} < {1})",
    "ge": "({0} >= {1})",
    "le": "({0} <= {1})",
    "eq": "({0} == {1})",
    "ne": "({0} != {1})",
    "logical_and": "({0} & {1})",
    "logical_or": "({0} | {1})",
    "where": "tl.where({0}, {1}, {2})",
}

PRELUDE = '''"""Generated by mlc. Do not edit.

One @triton.jit function per fused kernel. LAUNCH holds the grid and the
compile-time constants for each; the runtime reads it rather than recomputing
anything, so what runs is exactly what is written here.
"""

import triton
import triton.language as tl

# Transcendentals live in different places across Triton versions. Resolve
# once here so the kernels below stay version-independent.
try:
    from triton.language.extra import libdevice as _math
except ImportError:  # pragma: no cover - depends on the installed Triton
    try:
        from triton.language.extra.cuda import libdevice as _math
    except ImportError:
        _math = tl.math


@triton.jit
def _prod_combine(a, b):
    return a * b
'''


@dataclass
class LaunchSpec:
    """Grid and compile-time constants for one kernel launch."""

    grid: int
    constants: dict
    num_warps: int
    num_stages: int = 1


def next_pow2(n: int) -> int:
    return 1 << max(0, (n - 1).bit_length())


def choose_block(numel: int, cap: int) -> tuple[int, bool]:
    """Block size, and whether a bounds mask is needed.

    Prefers a block that divides the iteration space: an exact fit removes the
    mask from every load and store in the kernel.
    """
    cap = next_pow2(cap)
    if numel <= cap:
        block = max(next_pow2(numel), 32)
        return block, block != numel
    block = cap
    while block > 64 and numel % block != 0:
        block //= 2
    return block, numel % block != 0


def warps_for(block: int) -> int:
    if block <= 256:
        return 2
    if block <= 1024:
        return 4
    return 8


# --------------------------------------------------------------------------
# Expressions
# --------------------------------------------------------------------------

def render_const(v, dtype) -> str:
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        if v == math.inf:
            return 'float("inf")'
        if v == -math.inf:
            return '-float("inf")'
        if v != v:
            return 'float("nan")'
        return repr(v)
    raise TypeError(f"cannot emit constant {v!r}")


def render_expr(e: Expr, load_names: list[str]) -> str:
    if isinstance(e, Load):
        return load_names[e.slot]
    if isinstance(e, Ref):
        return e.name
    if isinstance(e, Const):
        return render_const(e.value, e.dtype)
    if isinstance(e, Cast):
        return f"({render_expr(e.x, load_names)}).to({TL_DTYPE[e.dtype]})"
    if isinstance(e, Call):
        tmpl = TRITON_FN.get(e.fn)
        if tmpl is None:
            raise KeyError(f"no Triton form for scalar function {e.fn!r}")
        return tmpl.format(*(render_expr(a, load_names) for a in e.args))
    raise TypeError(f"cannot emit {type(e).__name__}")


def _load_suffix(dtype: torch.dtype) -> str:
    return ".to(tl.float32)" if dtype in NARROW else ""


def store_value(src: str, dtype: torch.dtype) -> str:
    """Render a stored value, casting to the buffer dtype if needed.

    Parenthesised unconditionally: a bare integer literal followed by ``.to``
    is a syntax error in Python, and a constant store is exactly how a
    ``zeros_like`` feeding an embedding lookup comes out.
    """
    if dtype == torch.float32:
        return src
    return f"({src}).to({TL_DTYPE[dtype]})"


# --------------------------------------------------------------------------
# Pointwise kernels
# --------------------------------------------------------------------------

def emit_pointwise(k: PointwiseKernel, cfg: Config) -> tuple[str, LaunchSpec]:
    numel = k.numel
    block, needs_mask = choose_block(numel, cfg.pointwise_block)
    grid = (numel + block - 1) // block

    params = [f"in_ptr{i}" for i in range(len(k.inputs))]
    params += [f"out_ptr{i}" for i in range(len(k.outputs))]
    params.append("BLOCK: tl.constexpr")

    lines = [
        "@triton.jit",
        f"def {k.name}({', '.join(params)}):",
        f"    # iteration space {list(k.space)} = {numel} elements",
        "    pid = tl.program_id(0)",
        "    idx = pid * BLOCK + tl.arange(0, BLOCK)",
    ]
    if needs_mask:
        lines.append(f"    mask = idx < {numel}")
        guard = ", mask=mask, other=0.0"
        store_guard = ", mask=mask"
    else:
        lines.append(f"    # {numel} is a multiple of BLOCK: no bounds mask needed")
        guard = store_guard = ""

    load_names: list[str] = []
    for i, arg in enumerate(k.inputs):
        name = f"v{i}"
        load_names.append(name)
        expr = arg.index.render()
        lines.append(
            f"    {name} = tl.load(in_ptr{i} + ({expr}){guard}){_load_suffix(arg.dtype)}"
            f"  # {arg.value.name}"
        )

    for temp, expr in k.body:
        lines.append(f"    {temp} = {render_expr(expr, load_names)}")

    for i, arg in enumerate(k.outputs):
        src = render_expr(k.out_expr[arg.value.name], load_names)
        expr = arg.index.render()
        lines.append(
            f"    tl.store(out_ptr{i} + ({expr}), "
            f"{store_value(src, arg.dtype)}{store_guard})  # {arg.value.name}"
        )

    spec = LaunchSpec(grid=grid, constants={"BLOCK": block}, num_warps=warps_for(block))
    return "\n".join(lines), spec


# --------------------------------------------------------------------------
# Module assembly
# --------------------------------------------------------------------------

def generate_module(schedule: Schedule, cfg: Config) -> str:
    """Render an entire schedule as one importable Triton module."""
    parts = [PRELUDE]
    launches: dict[str, LaunchSpec] = {}
    for k in schedule.kernels:
        if isinstance(k, ExternKernel):
            continue
        if isinstance(k, PointwiseKernel):
            src, spec = emit_pointwise(k, cfg)
        elif isinstance(k, ReductionKernel):
            from .triton_reduction import emit_reduction

            src, spec = emit_reduction(k, cfg)
        else:
            raise TypeError(f"no Triton emitter for {type(k).__name__}")
        parts.append(src)
        launches[k.name] = spec

    table = ["LAUNCH = {"]
    for name, s in launches.items():
        table.append(
            f"    {name!r}: dict(grid=({s.grid},), constants={s.constants!r}, "
            f"num_warps={s.num_warps}, num_stages={s.num_stages}),"
        )
    table.append("}")
    parts.append("\n".join(table))
    return "\n\n\n".join(parts) + "\n"
